{{- if .Values.ssh.enabled }}
{{- with .Values.ssh.users }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "utils-helm-charts.fullname" $ }}-ssh
  labels:
    {{- include "utils-helm-charts.labels" $ | nindent 4 }}
data:
  users.yml: |-
    {{- toYaml . | nindent 4}}
{{- end}}
{{- end}}