{{- if .Values.alpine.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "utils-helm-charts.fullname" . }}-alpine
  labels:
    {{- include "utils-helm-charts.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.alpine.replicaCount }}
  selector:
    matchLabels:
      {{- include "utils-helm-charts.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: "alpine"
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 10 }}
      {{- end }}
      labels:
        {{- include "utils-helm-charts.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: "alpine"
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "utils-helm-charts.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-alpine
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.alpine.image.repository }}:{{ .Values.alpine.image.tag }}"
          imagePullPolicy: {{ .Values.alpine.image.pullPolicy }}
          {{- with .Values.alpine.envs }}
          env:
            {{- toYaml . | nindent 12}}
          {{- end}}
          {{- with .Values.alpine.ports }}
          ports:
            {{- toYaml . | nindent 12 }}
          {{- end}}
          command:
            - sleep
            - infinity
          volumeMounts:
          {{- with .Values.alpine.pvc}}
          {{- range .}}
            - name: {{.name}}
              mountPath: {{.mountPath}}
          {{- end}}
          {{- end}}
          {{- with .Values.alpine.additionalVolumeMounts}}
            {{- toYaml . | nindent 12}}
          {{- end}}
          {{- with coalesce .Values.alpine.resources .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end}}
      volumes:
      {{- with .Values.alpine.pvc}}
      {{- range .}}
        - name: {{.name}}
          persistentVolumeClaim:
            claimName: {{ include "utils-helm-charts.fullname" $ }}-{{.claimName}}
      {{- end}}
      {{- end}}
      {{- with .Values.alpine.additionalVolumes}}
        {{- toYaml . | nindent 8}}
      {{- end}}
{{- end}}
